name: post-meridian-agency_backend

services:
  django:
    command:
      - sh
      - -c
      - |
        python -m venv .env
        . .env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        python mysite/manage.py runserver 0.0.0.0:52356
    image: python:3.11.5-alpine
    ports:
      - 52356:52356
    volumes:
      - ./:/app
    working_dir: /app